# Generated by Django 3.0.8 on 2020-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
                ('descricao', models.TextField(blank=True, default='', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='oferta_images')),
                ('seo_oferta', models.CharField(default='', max_length=30)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
