# Generated by Django 3.0.8 on 2020-07-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_lista_ofertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista_ofertas',
            old_name='Preco',
            new_name='preco',
        ),
    ]
