# Generated by Django 3.0.8 on 2020-07-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_auto_20200724_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_ofertas',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
