# Generated by Django 3.0.8 on 2020-07-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_auto_20200724_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_ofertas',
            name='pertence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofertas.Oferta'),
        ),
    ]
