# Generated by Django 3.0.8 on 2020-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_auto_20200724_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
