# Generated by Django 2.0.1 on 2020-07-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=14)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='menu_logo')),
                ('seo_logo', models.CharField(max_length=35)),
            ],
        ),
    ]
