# Generated by Django 3.0.8 on 2020-07-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(default='Cliníca Horta Duarte', max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='seo_logo',
            field=models.CharField(max_length=45),
        ),
    ]
