# Generated by Django 3.0.8 on 2020-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200719_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(default='', max_length=30),
        ),
    ]
