# Generated by Django 3.0.8 on 2020-07-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200719_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='linkedln',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(default='', max_length=14),
        ),
    ]
