# Generated by Django 3.0.8 on 2020-07-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200719_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(default='', max_length=30),
        ),
    ]
