# Generated by Django 3.0.8 on 2020-07-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200719_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='seo_logo',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
    ]
