# Generated by Django 3.0.8 on 2020-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_empresa_descricao_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_preloader', models.CharField(default='', max_length=30)),
                ('descricao_preloader', models.TextField(blank=True, default='', null=True)),
                ('logo_preloader', models.ImageField(blank=True, null=True, upload_to='menu_logo')),
                ('seo_logo_preloader', models.CharField(blank=True, default='', max_length=45, null=True)),
            ],
        ),
    ]
