# Generated by Django 3.0.8 on 2020-07-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_preloader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preloader',
            new_name='Preloader_site',
        ),
    ]
