# Generated by Django 3.0.8 on 2020-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200719_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodape',
            name='horario2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='rodape',
            name='horario3',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
