# Generated by Django 3.0.8 on 2020-07-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200719_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banner', models.CharField(default='', max_length=30)),
                ('titulo1', models.CharField(default='', max_length=20)),
                ('titulo2', models.CharField(default='', max_length=20)),
                ('descricao', models.TextField(blank=True, default='', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='menu_banner')),
                ('seo_banner', models.CharField(blank=True, default='', max_length=45, null=True)),
            ],
        ),
    ]
