# Generated by Django 3.0.8 on 2020-07-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='titulo2',
            field=models.CharField(default='', max_length=30),
        ),
    ]
