# Generated by Django 3.0.8 on 2020-07-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='seo_imagem1',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='seo_imagem2',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='seo_imagem3',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='seo_imagem4',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
