# Generated by Django 3.0.8 on 2020-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamento',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='home_tratamento'),
        ),
    ]
