# Generated by Django 3.0.8 on 2020-07-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200720_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratamento',
            old_name='imagem1',
            new_name='imagem_antes',
        ),
        migrations.RenameField(
            model_name='tratamento',
            old_name='imagem2',
            new_name='imagem_depois',
        ),
        migrations.RenameField(
            model_name='tratamento',
            old_name='seo_imagem1',
            new_name='seo_imagem_antes',
        ),
        migrations.RenameField(
            model_name='tratamento',
            old_name='seo_imagem2',
            new_name='seo_imagem_depois',
        ),
    ]
