# Generated by Django 3.0.8 on 2020-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200720_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.CharField(default='', max_length=20)),
                ('titulo2', models.CharField(default='', max_length=30)),
                ('img_capa', models.ImageField(blank=True, null=True, upload_to='home_video')),
                ('url_video', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
