# Generated by Django 3.0.8 on 2020-07-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='titulo1',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='titulo2',
        ),
    ]
