# Generated by Django 3.0.8 on 2020-07-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200720_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='nome',
            field=models.CharField(default='', max_length=150),
        ),
    ]
