# Generated by Django 3.0.8 on 2020-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_videos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(default='', help_text='Nome da empresa', max_length=30),
        ),
    ]
