# Generated by Django 3.0.8 on 2020-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_banner', models.CharField(default='', max_length=30)),
                ('descricao_banner', models.TextField(blank=True, default='', null=True)),
                ('banner_imagem', models.ImageField(blank=True, null=True, upload_to='tratamentos_imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
