# Generated by Django 3.0.8 on 2020-07-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='descricao',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='oferta_images'),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='seo_tratamento',
            field=models.CharField(default='', max_length=30),
        ),
    ]
