# Generated by Django 3.0.8 on 2020-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0002_auto_20200724_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamento',
            name='seo_tratamento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
